apiVersion: v1
kind: LimitRange
metadata:
  name: my-default-resources
spec:
  limits:
  - default:
      cpu: 3
      memory: 3Gi
    defaultRequest:
      cpu: 2
      memory: 2Gi
    max:
      cpu: 8
      memory: 8Gi
    min:
      cpu: 1
      memory: 1Gi
    type: Container
