apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-limited-nginx
  name: my-limited-nginx
spec:
  containers:
  - image: nginx
    name: my-limited-nginx
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 2
        memory: 2Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always

status: {}
