apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-redis
  name: my-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-redis
  strategy: {}
  template:
    metadata:
      labels:
        app: my-redis
    spec:
      containers:
      - image: redis
        name: redis
